name: Java CI with Oracle JDK & MongoDB

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        # healthcheck để đảm bảo mongo sẵn sàng trước khi chạy test
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      # 1. Checkout code
      - name: Checkout source
        uses: actions/checkout@v3

      # 2. Setup Oracle JDK
      - name: Set up Oracle JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      # 3. Build & Test voi Maven
      - name: Build with Maven (UTF-8)
        run: mvn -B package --file pom.xml -Dproject.build.sourceEncoding=UTF-8